version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tharundb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build: .
    container_name: springboot-app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8084"
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
